version: '3.8'

services:
  latex-to-html:
    build: .
    container_name: latex-to-html
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - PORT=${PORT:-3000}
    restart: unless-stopped
